### PR TITLE
Refactor project structure by using Github's Actions, Issue Templates, and versioning

### PR DESCRIPTION
**Pull request by DenyThis**
Hi Anthon!

I hope you're doing well! I took a minute to reorganize your project a bit by using the power of Github a bit more. You can do cool things like versioning by creating releases accompanied by tags. I've also added Issue templates just in case you're interested in getting feedback from your users directly in Github. Lastly, I reorganized the documentation a bit more so that it can be easier to maintain in the future. Let me know what you think!

Thanks,
Deny

### CODE REVIEW

**Comment by DenyThis** [comment]
Hey Anthon! It's great that you like it!!

As for the commits - tl;dr they're essentially a no-op, I added them via Github's website, didn't love them, and removed them once again. All in favor of my previously committed ones with cool icons 🙂

Long version - I was playing around with GitHub autogenerated ones (even tho I had ones in hand from another project), so I ended up going for the ones I had. I used GitHub's own delete function to get rid of them, that's why I ended up with a bunch of commits (one per file, so kinda annoying). Hopefully they add a functionality to bulk-remove files from GitHub's website in the future! Now that I think about it, I should've just rolled back that commit! 😅
 
Also, yeah, I believe GitHub and Bitbucket are pretty similar in regard to actions/scripts. Of course, feel free to give me a shout if you need help understanding how the flow, well, flows!

Thanks!
Deny

**Comment by AnthonMS** [comment]
Hello @DenyThis, I have merged the PR. Again thank you for contributing your time and work!

Do you have a couple quick comments to make my life easier, so I don't have to go down the rabbit hole of figuring out how the releases work.

When you mention I have to use the "vX.Y.Z" format. Do you mean in a commit message? Can I trigger the npm build github action and make a new release directly from a commit message or do I need to go to the github releases page and manually create release?

The Bug and Feature request templates looks good and sure to make my life a little easier when bug reports are issued.

**Comment by DenyThis** [comment]
Hi Anthon! My apologies on the late response, but I noticed you were able to make a release! Pretty straightforward, right?

As for the HACS Validation job - it always does that when there's no "release" (i.e. the first time you run the new setup). Give it another go now that the release has deployed all the necessary compiled .js files for HACS, and it should move past this. I'm expecting it to pass now that you have most of the things that it requires to pass (i.e. Github Issues enabled, Github topics/tags, etc.). Of course, let me know if it doesn't work and I'll give you a hand!

As for the dist dir - it shouldn't affect users, as now it's just pulling it from the release built files instead of from the project itself. Worst case scenario we can put these back for backwards compatibility with any non-standard setups.

**Comment by AnthonMS** [comment]
No problem at all about the late reply. I do not see the option of manually triggering the workflows for build, validate and release. How do I trigger these?

**Comment by DenyThis** [comment]
Go to the action that failed and it should be in the top right corner of the screen  (the "re-run jobs" dropdown):

image

**Pull request merged**
